name: Build & Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_BUILD_TIME=$(date +%s)" > .env

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Android folder
        id: cache-android
        uses: actions/cache@v4
        with:
          path: android
          key: ${{ runner.os }}-android-${{ hashFiles('app.json', 'package.json', 'pnpm-lock.yaml') }}

      - name: Prebuild Android project
        if: steps.cache-android.outputs.cache-hit != 'true'
        run: npx expo prebuild --platform android

      - name: Decode Keystore
        run: |
          mkdir -p android
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/release.keystore

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASS }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASS }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
          name: Echo ${{ github.ref_name }}
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('manual-{0}', github.sha) }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
